// Generated by https://quicktype.io

export interface productDTO {
    id: number;
    name: string;
    dateCreated: string;
    lastModified: string;
    description: string;
    price: number;
    imageUrl: string;
    categories: categoryDTO[];
    tags: tagDTO[];
}

export interface categoryDTO {
    id: number;
    name: string;
    dateCreated: string;
    lastModified: string;
    description: string;
    isSubCategory: boolean;
    parentId: number;
}

export interface tagDTO {
    id: number;
    name: string;
    dateCreated: string;
    lastModified: string;
}
